### PR TITLE
Bump version to 1.2.27

### PR DESCRIPTION
**Pull request by rafaelclp**

### CODE REVIEW

**Comment by gverm** [comment]
@rafaelclp Can this be merged so the release makes it onto PyPi? :)

**Comment by rafaelclp** [comment]
@aylton-almeida

**Comment by rafaelclp** [comment]
@lorraneidevic

**Review by lorraneidevic — APPROVED** [review]

**Comment by gverm** [comment]
@rafaelclp Thanks for the version bump and the release, someone still needs to push it to PyPi though.

**Pull request merged**
